// ══════════════════════════════════════════════════════════════════════════
// ULTIMATE WEREWOLF DATA
// Physical cards are recorded by the moderator; rules are resolved manually.
// ══════════════════════════════════════════════════════════════════════════

const UW_ROLE_DEFINITIONS = [
  ["apprentice-seer", "Apprentice Seer", "village", "Become the Seer if the Seer is killed.", "", "If the Seer has died, wake as the new Seer and inspect a player."],
  ["aura-seer", "Aura Seer", "village", "At night, find the team of one player.", "At night, find out if someone has a non-ordinary role and what it is.", "Choose a player. Indicate that player's team."],
  ["beholder", "Beholder", "village", "Open your eyes the first night to see who the Seer is.", "", "Show the Beholder who the Seer is.", ""],
  ["big-bad-wolf", "Big Bad Wolf", "werewolf", "If the werewolves' target is beside you, you can kill any combination of your adjacent players. However, if the Leprechaun redirects the initial attack, none of your adjacent players die.", "You can attack one person beside the initial werewolf target.", "", "After the pack chooses, resolve adjacent kills if the condition applies."],
  ["bogeyman", "Bogeyman", "solo", "If the wolves can't decide who to kill, you do it for them. You win if all the night-active players are dead.", "", "", "Wake only if the wolves could not agree; choose their victim."],
  ["bodyguard", "Bodyguard", "village", "Choose a different player each night to protect. That player cannot be killed that night.", "", "Choose a player to protect tonight.", "Choose a different player to protect tonight."],
  ["cult-leader", "Cult Leader", "cult", "Each night, add a player to your cult. You win if all the players left alive are part of your cult.", "", "Choose a player to join the cult.", "Choose a player to join the cult; check whether all living players have joined."],
  ["cupid", "Cupid", "village", "Choose two players to be lovers. If one of those players dies, the other dies from a broken heart.", "", "Choose two players to become lovers.", ""],
  ["the-count", "The Count", "village", "The first night, you are told how many werewolves there are in each half of the village.", "", "Indicate the werewolf count in each half of the circle.", ""],
  ["diseased", "Diseased", "village", "If you are attacked by werewolves, the werewolves do not get fed the following night."],
  ["fruit-brute", "Fruit Brute", "werewolf", "If you are the last wolf left alive, you lose your appetite and cannot feed, but you are trying to root out all the villagers.", "", "", "Wake with the wolf pack unless the Fruit Brute is the last wolf alive."],
  ["ghost", "Ghost", "village", "Die the first night, then each day, write one-letter clues as a message from beyond (no names or initials).", "", "The Ghost dies. Explain the one-letter daily clue restriction.", ""],
  ["hunter", "Hunter", "village", "If you are killed, take someone down with you."],
  ["village-idiot", "Village Idiot", "village", "Always vote for players to die."],
  ["insomniac", "Insomniac", "village", "Each night, learn whether at least one of your neighbours has woken during the night.", "", "Indicate whether either neighbour woke.", "Indicate whether either neighbour woke."],
  ["lycan", "Lycan", "village", "You are a villager, but appear falsely to be a werewolf to the Seers and P.I."],
  ["wolf-man", "Wolf man", "werewolf", "You are the exact opposite of a Lycan.", "", "Wake with the wolf pack; Seers and the P.I. see you as a villager.", "Wake with the wolf pack; Seers and the P.I. see you as a villager."],
  ["martyr", "Martyr", "village", "Take the place of someone who has been killed before their role is revealed."],
  ["mason", "Mason", "village", "You know who the other Masons are.", "", "Wake all Masons so they recognise one another.", "", 3],
  ["mayor", "Mayor", "village", "Your vote counts twice when voting to eliminate a player if you reveal yourself."],
  ["old-hag", "Old Hag", "village", "At night, indicate a player who must leave the village the next day.", "", "Choose the player who must leave tomorrow.", "Choose the player who must leave tomorrow."],
  ["old-man", "Old Man", "village", "You die on night X, where X is the number of werewolves in the game plus one.", "", "Calculate and record the Old Man's death night.", "If this is the recorded night, the Old Man dies."],
  ["private-investigator", "P.I.", "village", "Inspect three adjacent players each night. You only know if at least one of them is malicious.", "Inspect three adjacent players on one night.", "Indicate whether any of the three adjacent players is malicious.", "Indicate whether any of the three adjacent players is malicious."],
  ["pacifist", "Pacifist", "village", "You cannot vote when eliminating a player."],
  ["priest", "Priest", "village", "On the first night, protect a player. The next attempt to kill that player fails. The night after that attempt, protect a different player.", "Protect one player from death caused at night, including vampire attacks.", "Choose a player for the persistent protection.", "After the protection blocks an attack, choose a different player."],
  ["prince", "Prince", "village", "You cannot be killed during the day."],
  ["seer", "Seer", "village", "Each night, point at a player and learn whether they are on the villager team, a vampire, or, if a werewolf, their exact powers.", "", "Choose a player and indicate their applicable team or exact werewolf powers.", "Choose a player and indicate their applicable team or exact werewolf powers."],
  ["spellcaster", "Spellcaster", "village", "At night, indicate a player who must not use their voice the following day.", "", "Choose the player who cannot speak tomorrow.", "Choose the player who cannot speak tomorrow."],
  ["tough-guy", "Tough Guy", "village", "You survive an extra day if attacked by werewolves at night."],
  ["troublemaker", "Troublemaker", "village", "Once per game, choose to have two elimination attempts on one day. If the votes are tied, you have wasted your chance."],
  ["amulet-of-protection", "The Amulet of Protection", "artifact", "Anyone who has this will not die. You must pass the Amulet to another player each day or it is destroyed."],
  ["white-wolf", "White Wolf (Miller's Hollow)", "werewolf", "Wake every night with the werewolves. Every other night, wake alone as well and kill anyone. You win only as the lone survivor.", "", "Wake with the pack, then wake alone and choose a target.", "Wake with the pack; on every other night, wake alone and choose a target."],
  ["thing", "Thing", "village", "Each night, tap a player sitting immediately next to you.", "", "Tap one adjacent player.", "Tap one adjacent player."],
  ["villager", "Villager", "village", "Find the werewolves and eliminate them during the day.", "", "", "", 20],
  ["witch", "Witch", "village", "Kill or save a player, once each per game.", "", "Optionally use the one-time save or kill.", "Optionally use the remaining one-time save or kill."],
  ["sorcerer", "Sorcerer", "werewolf", "You are a Seer on the Werewolf team. You only know if you found a werewolf, another Seer, or something else.", "", "Choose a player and indicate werewolf, Seer, or other.", "Choose a player and indicate werewolf, Seer, or other."],
  ["minion", "Minion", "werewolf", "Work with the werewolves or vampires to kill the villagers. The moderator decides which team you support.", "", "Show the Minion their assigned hostile team.", ""],
  ["werewolf", "Werewolf", "werewolf", "Eat a villager each night.", "", "Wake the wolf pack to recognise one another.", "Wake the wolf pack and choose a target.", 12],
  ["wolf-cub", "Wolf Cub", "werewolf", "If you die, the werewolves get two kills the following night.", "", "Wake with the wolf pack.", "Wake with the wolf pack; allow two kills if the Wolf Cub died since the last night."],
  ["dream-wolf", "Dream Wolf", "werewolf", "If a werewolf dies, you replace them. You do not wake until a werewolf dies.", "", "Do not wake unless a werewolf is already dead.", "Wake only after a werewolf has died; then join the wolf pack."],
  ["cursed", "Cursed", "village", "You are a villager until attacked by werewolves, at which time you become a werewolf.", "You become a vampire when attacked by vampires."],
  ["doppelganger", "Doppelgänger", "solo", "Select a player the first night. If that player dies, you secretly take that role.", "", "Choose the player whose role will be copied on death.", "If the chosen player has died, secretly adopt that role."],
  ["drunk", "Drunk", "village", "You are a villager until the third night, when you remember your real role.", "", "Record the Drunk's hidden role.", "On night 3, reveal and activate the hidden role."],
  ["hoodlum", "Hoodlum", "solo", "Indicate two players on the first night. If they die and you are alive at the end of the game, you win.", "", "Choose the two players required for the Hoodlum win.", ""],
  ["tanner", "Tanner", "solo", "You win only if you are killed."],
  ["lone-wolf", "Lone Wolf", "werewolf", "You are a werewolf, but you win only if you are the last wolf-team member alive.", "", "Wake with the wolf pack.", "Wake with the wolf pack."],
  ["vampire", "Vampire", "vampire", "Attack another player each night. They die if there is a nomination the next day.", "", "Wake the vampires to recognise one another and choose a target.", "Choose a target and record the nomination-triggered death.", 8],
  ["little-girl", "Little Girl", "village", "Like a villager, but each night you may discreetly peek. You die if the wolves correctly signal the moderator that you are the Little Girl.", "", "May discreetly watch the werewolves; resolve a wolf accusation if made.", "May discreetly watch the werewolves; resolve a wolf accusation if made."],
  ["wild-child", "Wild Child", "village", "On the first night, choose one role model. If the role model dies, you become a werewolf. Until then, you are a normal villager.", "", "Choose a role model.", "If the role model has died, convert the Wild Child to a werewolf."],
  ["sasquatch", "Sasquatch", "village", "You are a villager until a day ends without an elimination, in which case you become a werewolf.", "", "", "If yesterday ended without an elimination, convert the Sasquatch."],
  ["leprechaun", "Leprechaun", "village", "You can redirect werewolf attacks to players adjacent to the target, but you do not have to.", "", "After the wolf target, optionally redirect the attack to an adjacent player.", "After the wolf target, optionally redirect the attack to an adjacent player."],
  ["bloody-mary", "Bloody Mary", "solo", "If you die, kill someone from the team that killed you each night.", "", "", "If Bloody Mary is dead, choose an eligible player from the responsible team."],
  ["chupacabra", "Chupacabra", "solo", "Each night, select a player. If they are a werewolf, they die. If all wolves are dead, kill a player each night.", "", "Choose a player; kill them only if they are a werewolf.", "Choose a player; if no wolves live, any chosen player dies."],
  ["nostradamus", "Nostradamus", "solo", "Predict the winning team on the first night. If that team wins and you are alive at the end, you get a solo win. For the rest of the game you are a villager.", "", "Secretly record the predicted winning team.", ""],
  ["dire-wolf", "Dire Wolf", "werewolf", "On the first night, choose a companion. You die if they die, but if you die they do not die. You are on the wolf team.", "Put yourself in love on the first night.", "Choose the Dire Wolf's companion.", "Wake with the wolf pack and resolve the companion bond when applicable."],
  ["fortune-teller", "Fortune Teller (Miller's Hollow)", "village", "You know the exact roles of your inspectees, except for Wolf Man and Lycan, and the inspected player is not told.", "", "Choose a player and show their exact role, applying Wolf Man and Lycan exceptions.", "Choose a player and show their exact role, applying Wolf Man and Lycan exceptions."],
  ["moderator", "Moderator", "moderator", "Moderates the game. You cannot play without this role."],
  ["black-wolf", "Black Wolf", "werewolf", "A Spellcaster and a Werewolf combined.", "", "Wake with the wolf pack, then choose a player who cannot speak tomorrow.", "Wake with the wolf pack, then choose a player who cannot speak tomorrow."]
];

const UW_C = Object.fromEntries(UW_ROLE_DEFINITIONS.map(definition => {
  const [id, name, type, ability, variation = "", firstNight = "", otherNight = "", quantity = 1] = definition;
  const teamByType = {
    village: "village",
    werewolf: "werewolves",
    vampire: "vampires",
    cult: "cult",
    solo: "solo",
    artifact: "neutral",
    moderator: "neutral"
  };
  return [id, {
    id,
    name,
    type,
    team: teamByType[type],
    category: type,
    quantity,
    ab: ability,
    variation,
    fn_r: firstNight,
    on_r: otherNight
  }];
}));

const UW_FIRST_NIGHT = [
  { id: "_uw_night_rules", order: 1, title: "🌙 Night Rules", instructions: "All players close their eyes. Dead players may keep their eyes open and silently watch, but do not act." },
  { id: "doppelganger", order: 2 },
  { id: "cupid", order: 3 },
  { id: "dire-wolf", order: 4 },
  { id: "hoodlum", order: 5 },
  { id: "nostradamus", order: 6 },
  { id: "wild-child", order: 7 },
  { id: "priest", order: 8 },
  { id: "minion", order: 9 },
  { id: "mason", order: 10 },
  { id: "beholder", order: 11 },
  { id: "the-count", order: 12 },
  { id: "drunk", order: 13 },
  { id: "cult-leader", order: 14 },
  { id: "bodyguard", order: 15 },
  { id: "old-hag", order: 16 },
  { id: "spellcaster", order: 17 },
  { id: "thing", order: 18 },
  { id: "werewolf", order: 19 },
  { id: "wolf-man", order: 20 },
  { id: "wolf-cub", order: 21 },
  { id: "fruit-brute", order: 22 },
  { id: "lone-wolf", order: 23 },
  { id: "white-wolf", order: 24 },
  { id: "black-wolf", order: 25 },
  { id: "big-bad-wolf", order: 26 },
  { id: "dream-wolf", order: 27 },
  { id: "little-girl", order: 28 },
  { id: "leprechaun", order: 29 },
  { id: "vampire", order: 30 },
  { id: "witch", order: 31 },
  { id: "seer", order: 32 },
  { id: "apprentice-seer", order: 33 },
  { id: "aura-seer", order: 34 },
  { id: "sorcerer", order: 35 },
  { id: "private-investigator", order: 36 },
  { id: "fortune-teller", order: 37 },
  { id: "chupacabra", order: 38 },
  { id: "insomniac", order: 39 },
  { id: "old-man", order: 40 }
];

const UW_OTHER_NIGHT = [
  { id: "_uw_night_rules", order: 1, title: "🌙 Night Rules", instructions: "Dead players may silently watch the night. Dead players do not wake or become valid targets." },
  { id: "doppelganger", order: 2 },
  { id: "wild-child", order: 3 },
  { id: "drunk", order: 4 },
  { id: "sasquatch", order: 5 },
  { id: "priest", order: 6 },
  { id: "cult-leader", order: 7 },
  { id: "bodyguard", order: 8 },
  { id: "old-hag", order: 9 },
  { id: "spellcaster", order: 10 },
  { id: "thing", order: 11 },
  { id: "werewolf", order: 12 },
  { id: "wolf-man", order: 13 },
  { id: "wolf-cub", order: 14 },
  { id: "fruit-brute", order: 15 },
  { id: "lone-wolf", order: 16 },
  { id: "white-wolf", order: 17 },
  { id: "black-wolf", order: 18 },
  { id: "big-bad-wolf", order: 19 },
  { id: "dream-wolf", order: 20 },
  { id: "dire-wolf", order: 21 },
  { id: "little-girl", order: 22 },
  { id: "leprechaun", order: 23 },
  { id: "bogeyman", order: 24 },
  { id: "vampire", order: 25 },
  { id: "witch", order: 26 },
  { id: "bloody-mary", order: 27 },
  { id: "seer", order: 28 },
  { id: "apprentice-seer", order: 29 },
  { id: "aura-seer", order: 30 },
  { id: "sorcerer", order: 31 },
  { id: "private-investigator", order: 32 },
  { id: "fortune-teller", order: 33 },
  { id: "chupacabra", order: 34 },
  { id: "insomniac", order: 35 },
  { id: "old-man", order: 36 }
];

const UW = {
  id: "uw",
  name: "Ultimate Werewolf",
  emoji: "🐺",
  color: "#b7b8bd",
  tagline: "Physical-card moderator mode",
  desc: "Public discussion • Dead players watch nights • Manual resolution",
  C: UW_C,
  DIST: {},
  FIRST_NIGHT: UW_FIRST_NIGHT,
  OTHER_NIGHT: UW_OTHER_NIGHT,
  setupMode: "physical-cards",
  discussionMode: "public-only",
  deadCanVote: false,
  deadWatchNight: true,
  playerLimits: { min: 5, max: 75 },
  winnerGroups: [
    { id: "village", label: "Village", emoji: "🏘️" },
    { id: "werewolves", label: "Werewolves", emoji: "🐺" },
    { id: "vampires", label: "Vampires", emoji: "🧛" },
    { id: "cult", label: "Cult", emoji: "🕯️" }
  ],
  soloWinnerRoles: ["bogeyman", "white-wolf", "doppelganger", "hoodlum", "tanner", "lone-wolf", "bloody-mary", "chupacabra", "nostradamus"]
};
